--- #YAML:1.0
name:               re-engine-RE2
version:            0.08
abstract:           RE2 regex engine
author:
    - David Leadbeater <dgl@dgl.cx>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::CppGuess:  0
    Test::More:          0.88
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    repository:  https://github.com/dgl/re-engine-RE2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
