---
abstract: 'RE2 regex engine'
author:
  - 'David Leadbeater <dgl@dgl.cx>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::CppGuess: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: re-engine-RE2
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: https://github.com/dgl/re-engine-RE2
version: 0.11
